# Generated by Django 3.0.7 on 2020-06-21 02:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_map_app', '0002_point_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='longitude/latitude'),
        ),
    ]
