# Generated by Django 3.0.7 on 2020-06-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_map_app', '0003_point_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
