# Generated by Django 3.0.7 on 2020-06-27 14:10

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = 'data/data.json'


def load_data(apps, schema_editor):
    Point = apps.get_model('dj_map_app', 'Point')

    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name', 'no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Point(text=name, geom=location, owner_id='1').save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('dj_map_app', '0004_point_date_updated'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
